# branches:
#   only:
#     master

git:
  - sparse_checkout: !figs/*
  - sparse_checkout: !output/*
  - sparse_checkout: !runs/*

os:
  - linux
dist: xenial   # required for Python >= 3.7
language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'
  # - "3.7-dev"  # 3.7 development branch
  # - "3.8-dev"  # 3.8 development branch
  # - "nightly"  # nightly build

matrix:
  include:
    - python: '3.7'
      env: DOCS=1
  allow_failures:
    - python: '2.7'

cache: pip

install:
  - pip install pipenv nox
  # - pipenv --bare install --deploy --dev

script:
  - nox -s lint
  - nox -s tests  # -- safety
  - if [[ $DOCS == 1 ]]; then nox -s docs; fi
